---
- name: If firewalld enabled, open api port
  ansible.posix.firewalld:
    port: "{{ kube_port }}/tcp"
    zone: trusted
    state: enabled
    permanent: true
    immediate: true

- name: Distributing custom selinux policies
  copy:
    src: "./nginx.te"
    dest: "/nginx.te"
  register: custom_policies_output

- name: Build and reload custom selinux policy files
  shell: |
    checkmodule -M -m -o nginx.mod nginx.te
    semodule_package -o nginx.pp -m nginx.mod 
    /usr/sbin/semodule -u /nginx.pp
  args:
    chdir: "/"
  when: custom_policies_output.changed