apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-frontend
  namespace: temporal
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  tls:
    - secretName: temporal-frontend-tls
      hosts:
      - temporal-frontend.local
  rules:
    - host: temporal-frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-frontend
                port:
                  number: 7233
