apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-frontend
  namespace: temporal
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: temporal-frontend.local
spec:
  tls:
    - secretName: temporal-frontend-tls
      hosts:
      - temporal-frontend.local
  rules:
    - host: temporal-frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-frontend
                port:
                  number: 7233
