---
- name: Undo cluster setup
  hosts: k3s_cluster
  gather_facts: true
  become: true
  tasks:
    - name: Run K3s Uninstall script [server]
      when: "'server' in group_names"
      ansible.builtin.command:
        cmd: k3s-uninstall.sh
        removes: /var/lib/rancher/k3s/*
    - name: Run K3s Uninstall script [agent]
      when: "'agent' in group_names"
      ansible.builtin.command:
        cmd: k3s-agent-uninstall.sh
        removes: /var/lib/rancher/k3s/*
    - name: Remove user kubeconfig
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube/config
        state: absent
    - name: Remove k3s.service
      ansible.builtin.file:
        path: "/etc/systemd/system/k3s.service*"
        state: absent

- name: Undo nginx setup
  hosts: load_balancer
  gather_facts: true
  become: true
  tasks:
    - name: Stop nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped
    - name: Uninstall nginx 1
      yum:
        name: 
          - nginx
          - nginx-full
          - nginx-common
          - nginx-core
          - policycoreutils
          - libselinux-python3
          - policycoreutils-python
        state: absent

    - name: Remove nginx config file
      ansible.builtin.file:
        path: "/etc/nginx/*"
        state: absent