grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      kubernetes.io/ingress.class: traefik
    path: /
    pathType: Prefix

    hosts:
      - grafana.local
    tls:
    - secretName: grafana-ingress-tls
      hosts:
        - grafana.local
alertmanager:
  enabled: false