---
- name: Copy nginx config file
  vars:
    target_servers: "{{ groups['load_balancer'] }}"
  ansible.builtin.template:
    src: "nginx-lb.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0755

- name: Disable and check nginx service
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    state: stopped
    enabled: true

- name: Enable and check nginx service
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    state: started
    enabled: true
