---
- name: Ensure nginx is at the latest version
  yum:
    name: 
      - nginx
      - nginx-mod-stream
    state: latest

- name: install selinux deps
  yum:
    name: 
      - policycoreutils
      - libselinux-python3
      - policycoreutils-python
    state: latest