apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: charts/temporal-test
    repoURL: https://github.com/gosharo/k3s-ansible
    targetRevision: main
    helm:
      values: |
        tests:
          namespaceName: benchtest
          namespaceRetention: "1"
          frontendAddress: temporal-frontend.temporal.svc.cluster.local:7233
          prometheusURL: "http://prometheus-server"
        ingress:
          enabled: false
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
          hosts:
            - host: temporal-test.local
              paths:
                - /
          tls: 
           - secretName: temporal-test-tls
             hosts:
               - temporal-test.local
