apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: temporal
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: charts/temporal
    repoURL: https://github.com/gosharo/k3s-ansible
    targetRevision: main
    helm:
      values: |
        web:
          ingress:
            enabled: true
            annotations: 
              kubernetes.io/ingress.class: nginx
              traefik.frontend.rule.type: PathPrefix
              cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
            hosts:
              - temporal.local
            tls:
            - secretName: temporal-tls
              hosts:
                - temporal.local
        grafana:
          enabled: false
        prometheus:
          enabled: false
        elasticsearch:
          enabled: false
        cassandra:
          enabled: false
        server:
          metrics:
            annotations:
              enbaled: false
            serviceMonitor:
              enabled: true
          config:
            persistence:
              default:
                cassandra:
                  port: 9042
                  hosts:
                    - cassandra.temporal.svc.cluster.local
              visibility:
                cassandra:
                  port: 9042
                  hosts:
                    - cassandra.temporal.svc.cluster.local